[build]
  command = "dotnet publish -c Release"
  publish = "bin/Release/net9.0/publish/wwwroot"
  functions = "netlify/functions"

[build.environment]
  DOTNET_VERSION = "9.0.100"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
